### PR TITLE
fix Windows color

### PR DESCRIPTION
**Pull request by mattn**
brename

### CODE REVIEW

**Comment by shenwei356** [comment]
Thank you so much! Finally solve it. I can fix other tools now! 😄

**Comment by shenwei356** [comment]
It's not perfect yet. `[ERRO]` should be red too :(

**Comment by shenwei356** [comment]
Oh, no!

https://github.com/op/go-logging/blob/master/format.go#L186

> Colors on Windows is unfortunately not supported right now and is currently a no-op.

But I remembered it supports several months ago.

**Comment by mattn** [comment]
The author of go-logging maybe not know go-colorable.

**Comment by shenwei356** [comment]
Yes no forks of go-logging tried to fix it.

**Comment by shenwei356** [comment]
Can you help to improve go-logging with go-colorable. I tried and failed.

**Comment by mattn** [comment]
put same change in above into here https://github.com/op/go-logging/blob/970db520ece77730c7e4724c61121037378659d9/logger.go#L132

**Comment by shenwei356** [comment]
More code to be added: https://github.com/op/go-logging/blob/970db520ece77730c7e4724c61121037378659d9/log_windows.go#L104

**Comment by mattn** [comment]
1. remove log_windows.go
2. put build-constraints for windows into log_nix.go

**Comment by shenwei356** [comment]
Thanks you @mattn , it works !!!!

I'll create a pull request to go-logging.

**Pull request merged**
