### PR TITLE
ArchLinux AUR package

### PR DESCRIPTION
**Pull request by efournival**
Hi,

I have packaged your utility in the ArchLinux User Repository (AUR):
https://aur.archlinux.org/packages/brename/

The commit add a new installation method for AUR users in the README.

### CODE REVIEW

**Comment by shenwei356** [comment]
thank you @efournival

**Comment by shenwei356** [comment]
Is the `glibc` needed as a dependency? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brename#n10 . Most of the time, these's no dependency for go binaries.

**Comment by efournival** [comment]
Yes. It was suggested by `namcap` (the package verification tool), here is the output if I comment the line `depends=('glibc')`:
```
$ makepkg
$ namcap brename-2.2.0-1-x86_64.pkg.tar.xz 
brename E: Dependency glibc detected and not included (libraries ['usr/lib/libc.so.6', 
'usr/lib/libpthread.so.0'] needed in files ['usr/bin/brename'])
```

Indeed, running `ldd` provides the following output:
```
$ ldd /usr/bin/brename 
	linux-vdso.so.1 (0x00007ffe27ce8000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fd9a6560000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fd9a61bc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd9a677e000)
```

Considering [this thread](https://groups.google.com/forum/#!topic/golang-nuts/B8WPRKajvtI) and [this document](https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/edit), you are importing os-related packages which causes linking against `libc`.

**Comment by shenwei356** [comment]
I see. Thank you so much @efournival .

**Comment by efournival** [comment]
No problem :)

**Pull request merged**
